"""add priority

Revision ID: 727a80c217d9
Revises: f227176accd5
Create Date: 2026-06-24 15:17:59.396813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '727a80c217d9'
down_revision: Union[str, Sequence[str], None] = 'f227176accd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum('H', 'M', 'L', name='priority'), nullable=True))
    op.drop_column('tasks', 'priotity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priotity', postgresql.ENUM('H', 'M', 'L', name='priority'), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
