"""add timestamps

Revision ID: f227176accd5
Revises: 5f9c5a0bca59
Create Date: 2026-06-10 20:40:43.743816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f227176accd5'
down_revision: Union[str, Sequence[str], None] = '5f9c5a0bca59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with nullable first
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Update existing rows with current time
    op.execute("UPDATE tasks SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE tasks SET updated_at = NOW() WHERE updated_at IS NULL")
    
    # Make NOT NULL
    op.alter_column('tasks', 'created_at', nullable=False)
    op.alter_column('tasks', 'updated_at', nullable=False)
    
    # Fix invalid status values before converting to enum
    op.execute("UPDATE tasks SET status = 'pending' WHERE status NOT IN ('pending', 'in_progress', 'completed')")
    
    # Now convert to enum with explicit casting
    op.alter_column('tasks', 'status',
           existing_type=sa.VARCHAR(),
           type_=sa.Enum('pending', 'in_progress', 'completed', name='taskstatus'),
           existing_nullable=True,
           postgresql_using='status::taskstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('pending', 'in_progress', 'completed', name='taskstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
